/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osjava_jdbc_sqlite_ResultSet */

#ifndef _Included_org_osjava_jdbc_sqlite_ResultSet
#define _Included_org_osjava_jdbc_sqlite_ResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osjava_jdbc_sqlite_ResultSet
 * Method:    proxyCloseStatement
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_osjava_jdbc_sqlite_ResultSet_proxyCloseStatement
  (JNIEnv *, jobject);

/*
 * Class:     org_osjava_jdbc_sqlite_ResultSet
 * Method:    populateRows
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_osjava_jdbc_sqlite_ResultSet_populateRows
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
