/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osjava_jdbc_sqlite_Driver */

#ifndef _Included_org_osjava_jdbc_sqlite_Driver
#define _Included_org_osjava_jdbc_sqlite_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osjava_jdbc_sqlite_Driver
 * Method:    proxyConnect
 * Signature: (Ljava/lang/String;)Ljava/sql/Connection;
 */
JNIEXPORT jobject JNICALL Java_org_osjava_jdbc_sqlite_Driver_proxyConnect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
