/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osjava_jdbc_sqlite_Statement */

#ifndef _Included_org_osjava_jdbc_sqlite_Statement
#define _Included_org_osjava_jdbc_sqlite_Statement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osjava_jdbc_sqlite_Statement
 * Method:    executeSQL
 * Signature: (Ljava/lang/String;Ljava/sql/Connection;Ljava/sql/ResultSet;)V
 */
JNIEXPORT void JNICALL Java_org_osjava_jdbc_sqlite_Statement_executeSQL
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
