<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>OSJava.org: ${TITLE}</title>
    <link href="http://www.osjava.org/css/master.css" rel="stylesheet" type="text/css">
    <link href="css/pyjamas.css" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>
  </head>

  <body bgcolor="white">
    <div id="banner"><table width="100%"><tr><td><a href="/"><img border="0" alt="OSJava" src="http://www.osjava.org/images/osjava.gif" align="left"></a></td></tr></table></div>
    <div id="breadcrumbs">
      <div id="tagline">
        <a href="http://www.osjava.org/">OSJava.org</a>: ${TITLE}
      </div>
      <div id="copyright" align="right">&copy;2003,2004</div>
    </div>
