/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osjava_jdbc_sqlite_Connection */

#ifndef _Included_org_osjava_jdbc_sqlite_Connection
#define _Included_org_osjava_jdbc_sqlite_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osjava_jdbc_sqlite_Connection
 * Method:    proxyClose
 * Signature: (I)Z
 */
JNIEXPORT void JNICALL Java_org_osjava_jdbc_sqlite_Connection_proxyClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
